#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Dec 14th, 2014
# -----------------------------------------------------------------------------


if [ ! -f /data/forge-1.10.2-12.18.2.2099-installer.jar ]
then
    #curl "https://s3.amazonaws.com/Minecraft.Download/versions/1.10.2/minecraft_server.1.10.2.jar" -o /data/minecraft_server.jar
    cp /opt/minecraft/forge-1.10.2-12.18.2.2099-installer.jar /data/forge-1.10.2-12.18.2.2099-installer.jar
    mkdir /data/jar
    cp /opt/minecraft/minecraft_server.1.10.2.jar /data/jar/minecraft_server.1.10.2.jar
    echo "Copied! "
    cd data; java -jar forge-1.10.2-12.18.2.2099-installer.jar -installServer
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data; java -Xmx2G -jar forge-1.10.2-12.18.2.2099-universal.jar nogui

